### ISSUE TITLE
Make bitcoin-dca work for more coins than just... bitcoin 

### ISSUE THREAD

**Issue by Nebukadnezzar1** [Jorijn/bitcoin-dca#126]
First and foremost: Thanks a lot for this great dca solution! 
But since you can always make a great tool even "better", I'd like to address the following feature request:

It would be great if we could dca more coins than "just" Bitcoin using your solution. 
In a "best case scenario" the supported coins would be those enlisted within your integrated Exchanges.

**Comment by Jorijn** [comment]
Hey @Nebukadnezzar1 

Thanks for taking the time to write an issue and think about making this project better.

I feel that Bitcoin is the only one that matters and makes a difference. While that doesn't mean altcoins aren't worth looking at, I did decide that they're not worth my time as it is too difficult to keep up with the gazillion new projects each week. I made the deliberate choice only to allow Bitcoin to support my vision.

While this project is the primary one that received support and new bug fixes, features, and updates, I know that @Sebastix created a fork of this project to support various altcoins. However, it is not very up to date with the latest developments. It might fit you: https://github.com/Sebastix/crypto-dca

Best of luck in your search for a DCA tool! 

Jorijn
