### ISSUE TITLE
Error on RPi during withdrawal from Bitvavo

### ISSUE THREAD

**Issue by orosseel** [Jorijn/bitcoin-dca#150]
Hello Jorijn,

First of all, thanks for making this script available! And I used your affiliate link on Bitvavo.

Unfortunately, I am getting an error running this command on RPi:
$(command -v docker) run --rm -it --env-file=/home/pi/Docker/bitcoin-dca/.bitcoin-dca ghcr.io/jorijn/bitcoin-dca:latest withdraw --all --yes --no-ansi

Error:
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Jorijn\Bitcoin\Dca\EventListener\XPubAddressUsedListener::__construct() must be an instance of Jorijn\Bitcoin\Dca\Component\AddressFromMasterPublicKeyComponent, instance of Jorijn\Bitcoin\Dca\Component\ExternalAddressFromMasterPublicKeyComponent given, called in /app/var/cache/container.php on line 509 and defined in /app/src/EventListener/XPubAddressUsedListener.php:28
Stack trace:
#0 /app/var/cache/container.php(509): Jorijn\Bitcoin\Dca\EventListener\XPubAddressUsedListener->__construct()
#1 /app/var/cache/container.php(174): BitcoinDcaContainer->getEventListener_XpubAddressUsedService()
#2 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(267): BitcoinDcaContainer->{closure}()
#3 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}()
#4 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callList in /app/src/EventListener/XPubAddressUsedListener.php on line 28

I already found an issue with a similar error but it was related to Kraken.

Thanks for helping me!

**Comment by Jorijn** [comment]
Hey @orosseel 

Thanks for using my affiliate link! 

I am very sorry, as it seems a minor bug crept into the code, which went unnoticed for quite some time. I just pushed a patch that should solve your problem. I will create a new version later today. If you follow the upgrade instructions to bump your local image to the latest version, you shouldn't experience this error.

Best of luck, DCA'ing! 

Jorijn

**Comment by Jorijn** [comment]
v1.6.1 contains the fix :-)

**Comment by orosseel** [comment]
What a quick response and fix! Thanks, @Jorijn!
