### ISSUE TITLE
Dockerless version?

### ISSUE THREAD

**Issue by AbelLykens** [Jorijn/bitcoin-dca#27]
Hey, would like to use the tool, but I have a love-hate relationship with Docker.

If I am the only one who'd like a standalone version, then ignore me, but I would really like to be able to run dca without needing docker ;).

Wonder what you think.

**Comment by Jorijn** [comment]
Hey @AbelLykens 

You can, it's a PHP application based on PHP 7.4. You can clone the repository, install all the dependencies with `composer install` (see: https://getcomposer.org/).

After that, you should be able to add configuration to an `.env` file in the project directory and run `./bin/bitcoin-dca` to fire off the tool. The rest of the steps should be pretty self explanatory. 

If you need any more help, let me know.

Happy DCA'ing! :-)
