### ISSUE TITLE
Documentation for XPUB is missing code blocks

### ISSUE THREAD

**Issue by jphorn** [Jorijn/bitcoin-dca#50]
**Describe the bug**
The [documentation page for XPUB](https://bitcoin-dca.readthedocs.io/en/latest/xpub-withdraw.html#verifying-the-configured-xpub) is missing its code samples, making the steps impossible to reproduce.

_(I was able to find the needed code samples by editing the file on Github, so all good for me)_

**To Reproduce**
1. Go to https://bitcoin-dca.readthedocs.io/en/latest/xpub-withdraw.html#verifying-the-configured-xpub or [its Git counterpart](https://github.com/Jorijn/bitcoin-dca/blob/master/docs/xpub-withdraw.rst)
2. See the page is missing all its (code) samples.

**Expected behavior**
See all (code) samples as all the other documentation page.

**Comment by mijndert** [comment]
Hi @jphorn, it's now fixed! 👍

**Comment by jphorn** [comment]
Looks beautiful :-) Thanks @mijndert 👍
