### ISSUE TITLE
Documentation: some code blocks are not visible

### ISSUE THREAD

**Issue by rachidbm** [Jorijn/bitcoin-dca#80]
**Describe the bug**
Some `.. code-blocks` are not visible in the Documentation.

**To Reproduce**
1. Go to https://bitcoin-dca.readthedocs.io/en/latest/xpub-withdraw.html
2. Scroll down to `Verifying the configured XPUB`
3. See no code blocks

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2752952/128648682-0e17cfec-c582-47f0-ab1a-4a911113bde4.png)

**Comment by Jorijn** [comment]
Thanks for reporting! Fixed in d4902f32d9ed7222d60209893c7aa37a93c16214.
